import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '@/components/Header';
import './globals.css';

// ! Remove pre production
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-hola-cream text-hola-ink font-body`}
      >
        <Header />
        <main>{children}</main>
        <div className="fixed bottom-0 right-0 z-40 mr-8 mb-8 flex flex-col gap-2">
          <Link href="/theme" className=" bg-zinc-100 border-black px-4 py-1.5 border-2 shadow-2xl rounded-xl">
            THEME
          </Link>
          <Link href="/colors" className=" bg-zinc-100 border-black px-4 py-1.5 border-2 shadow-2xl rounded-xl">
            COLORS
          </Link>
          <Link href="/studio" className=" bg-zinc-100 border-black px-4 py-1.5 border-2 shadow-2xl rounded-xl">
            CMS
          </Link>
        </div>
      </body>
    </html>
  );
}
